name: Add contestant
on:
  issues:
    types:
      - labeled
permissions:
  issues: write
  contents: write
jobs:
  add-contestant:
    if: github.event.label.name == 'register'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3 # Checkout the repository content to github runner
      - name: Setup Python Version
        uses: actions/setup-python@v3
        with:
          python-version: 3.12 # Install needed python version
      - name: Install Python depenencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: requirements.txt
      - name: Execute Python scripts
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions.github.com
          python3 src/update_users.py "${{ github.event.issue.body }}"
          git add data/users.json
          git commit -m "GH ACTION added user"
          python3 src/fetch.py
          git add README.md
          git commit -m "GH ACTION updated leaderboard"
          git push
      - name: Close issue
        run: gh issue close ${{ github.event.issue.number }} -c "Added"
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions

